### ISSUE TITLE
Connection Failures: Health Check Target always hitting 0.200

### ISSUE THREAD

**Issue by kethcode** [smartcontracts/simple-optimism-node#1]
so I am running into weirdness on the health check.  Perhaps I'm configuring it wrong.

an Alchemy L2 Mainnet RPC for Health Check, and an Alchemy L1 Mainnet RPC for Fault and Data, should work fine, yes?  I have also tried https://mainnet.optimism.io/  and the sequencer URI with no change.  I suspect it may an issue with my config or network, but wanted to confirm.

![image](https://user-images.githubusercontent.com/94415863/171514437-81e0d2af-e3d1-48c1-b3b4-04216070994b.png)

**Comment by smartcontracts** [comment]
Ah oops this is expected behavior until we merge https://github.com/ethereum-optimism/optimism/pull/2335

**Comment by smartcontracts** [comment]
Basically Geth doesn't start syncing until the DTL is fully synced, so the L2Geth RPC doesn't open up, so the connection to the target errors out. If you want a temporary solution, you can set this as your L2Geth image tag in your .env file: prerelease-0.0.0-test-parallel-sync-2

**Comment by kethcode** [comment]
excellent, that did fix it, thank you.

another question...  in the compose yml, is health check and fault detector supposed to share a port?

![image](https://user-images.githubusercontent.com/94415863/171542731-38922e92-7e75-47ea-baf7-7d5e7ab3881f.png)

**Comment by smartcontracts** [comment]
Format for ports are:

<external>:<internal> 

So in this case both services run metrics servers on 7300 internally but are exposed on different ports externally (on localhost).

**Comment by kethcode** [comment]
ah, ok.  thanks.  closing ticket.
