### ISSUE TITLE
Running Optimism node with local Ethereum RPC

### ISSUE THREAD

**Issue by dandavid3000** [smartcontracts/simple-optimism-node#100]
Hi !

I cannot run the optimism node with docker compose from a local Ethereum RPC.
It requires a flag --net=host to use local network. However, I tried to add [here](https://github.com/smartcontracts/simple-optimism-node/blob/main/docker-compose.yml#L77)

`network_mode: "host"`

There was a conflict between docker configurations. It says

`"host" network_mode is incompatible with port_bindings`

Does anyone know how to solve this issue?

Thank you

**Comment by dandavid3000** [comment]
@smartcontracts Could you please help or give any suggestions ? 
I'd like to use my local Ethereum RPC instead of other providers (Alchemy, quicknode pro)
Let's say my local node is at 127.0.0.1:8649
I setup 
`OP_NODE__RPC_ENDPOINT=http://127.0.0.1:8649`
But I cannot get data from localhost. What should I change in the config in order to achieve this?
Thanks

**Comment by tajelp** [comment]
Same problem here. I get this:

```
simple-optimism-node-healthcheck-1     | {"level":50,"time":1694893509505,"msg":"target client not connected"}
```

**Comment by dandavid3000** [comment]
Do not use docker but run manually op-node and op-geth from the [official guide](https://community.optimism.io/docs/developers/nodes/mainnet/)
