### ISSUE TITLE
Node not progressing after Bedrock upgrade

### ISSUE THREAD

**Issue by bmalepaty** [smartcontracts/simple-optimism-node#104]
After bedrock block, the node is not syncing

Docker-compose file:
[docker-compose.yaml.txt](https://github.com/smartcontracts/simple-optimism-node/files/13412990/docker-compose.yaml.txt)

**op-geth Logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/cd0058ac-493d-4160-8ee6-6360aeeb7267)

**op-node Logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/b8228b76-9dad-4212-92d8-f63253de49ef)

**Healthcheck Logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/2ba57512-bd77-4c67-aace-2cacd7c7af3b)

**FaultDetector Logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/e370018a-5a06-4e8e-929a-6b29e5948168)

**Comment by Chomtana** [comment]
On op-node logs, it say "Incorrect L2 RPC chain id 1, expected 10" which means that op-geth snapshot is not downloaded correctly.

**Comment by Chomtana** [comment]
You should delete old pre-bedrock data and download snapshot from https://datadirs.optimism.io/mainnet-bedrock.tar.zst

And extract into

/NewDisk117Machine/simple-optimism-node/data/shared

And try running node again
