### ISSUE TITLE
Add comment for op-sepolia support

### ISSUE THREAD

**Issue by smartcontracts** [smartcontracts/simple-optimism-node#113]
https://github.com/smartcontracts/simple-optimism-node/blob/45672749013e50dd6bbc75d05ce46e4a8b50fd3d/.env.example#L5

Since op-sepolia is supported now we should probably update this comment.

**Comment by Chomtana** [comment]
Changed the comment in .env.example from op-goerli -> op-sepolia (c8a9415f5d11cd9540c1e85ff93d44a2300bb5fe)
