### ISSUE TITLE
bedrock init error 66 :  Decompression error : ERROR_contentChecksum_invalid

### ISSUE THREAD

**Issue by BoogalooLi** [smartcontracts/simple-optimism-node#118]
I want to run a fullnode by docker, but the logs in bedrock-init shows snapshot checksum invalid.

> simple-optimism-node-bedrock-init-1  | gid   |stat|avg speed  |path/URI
> simple-optimism-node-bedrock-init-1  | ======+====+===========+=======================================================
> simple-optimism-node-bedrock-init-1  | dfae37|OK  |   106MiB/s|//downloads/bedrock.tar.lz4
> simple-optimism-node-bedrock-init-1  | 
> simple-optimism-node-bedrock-init-1  | Status Legend:
> simple-optimism-node-bedrock-init-1  | (OK):download completed.
> simple-optimism-node-bedrock-init-1  | Extracting bedrock.tar...
> simple-optimism-node-bedrock-init-1  | Error 66 : Decompression error : ERROR_contentChecksum_invalid 
> simple-optimism-node-bedrock-init-1  | tar: Child returned status 66
> simple-optimism-node-bedrock-init-1  | tar: Error is not recoverable: exiting now

**Comment by BoogalooLi** [comment]
> This is a bug in lz4 that's installed by apt. Will try to fix it
> 
> [pierrec/lz4#27](https://github.com/pierrec/lz4/issues/27)

Can I fix it manually? Thank you

**Comment by Chomtana** [comment]
You can manually stop docker compose (docker compose down), extract bedrock.tar.lz4 in the docker volume folder and then start docker again (docker compose up -d)

cd to docker volume directory as root

```
cd /var/lib/docker/volumes/simple-optimism-node_torrent_downloads/_data
```

(Path may differ if not using Ubuntu)

And extract bedrock.tar.lz4 to `/var/lib/docker/volumes/simple-optimism-node_op_geth/_data` (Different volume)

**Comment by BoogalooLi** [comment]
> You can manually stop docker compose (docker compose down), extract bedrock.tar.lz4 in the docker volume folder and then start docker again (docker compose up -d)
> 
> cd to docker volume directory as root
> 
> ```
> cd /var/lib/docker/volumes/simple-optimism-node_torrent_downloads/_data
> ```
> 
> (Path may differ if not using Ubuntu)
> 
> And extract bedrock.tar.lz4 to `/var/lib/docker/volumes/simple-optimism-node_op_geth/_data` (Different volume)

After extracting the data and rerun the docker containers, bedrock-init download the file again.

**Comment by 0xpanoramix** [comment]
I assume it tries to download again because the bedrock-init checks for the existence of a `/shared/initialized.txt` file which is only created after the script has completed.

The check is made [here](https://github.com/smartcontracts/simple-optimism-node/blob/300068f8fa4e4d7f7adb56ccb23cdc1e82f92fa4/scripts/init-bedrock.sh#L16-L19) while the file is created [here](https://github.com/smartcontracts/simple-optimism-node/blob/300068f8fa4e4d7f7adb56ccb23cdc1e82f92fa4/scripts/init-bedrock.sh#L59-L60).

So maybe try to create a `/shared/initialized.txt` file in the volume and run again?

cc @BoogalooLi @Chomtana

**Comment by Chomtana** [comment]
Yes as @0xpanoramix said create an `initialized.txt` file in `/var/lib/docker/volumes/simple-optimism-node_shared/_data`.

```
touch /var/lib/docker/volumes/simple-optimism-node_shared/_data/initialized.txt
```

**Comment by BoogalooLi** [comment]
Thanks a lot. I'll try it. Thanks.
