### ISSUE TITLE
Add the OP_NODE_L1_BEACON flag

### ISSUE THREAD

**Issue by fala13** [smartcontracts/simple-optimism-node#125]
Flag OP_NODE_L1_BEACON was introduced to Optimism in:
https://github.com/ethereum-optimism/optimism/pull/9120

Base already has it in .env:
https://github.com/base-org/node/releases/tag/v0.7.1

(and maybe bump to op-node docker v.1.5.1 while updating).

**Comment by Chomtana** [comment]
Thanks, flag already added and bumped on the recent merge
