### ISSUE TITLE
When I run a new node, I encounter this error message:Waiting for Bedrock node to initialize

### ISSUE THREAD

**Issue by wetezos** [smartcontracts/simple-optimism-node#129]
When I run a new node, I encounter this error message:

noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
errtrace        off
vi              off
pipefail        off
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...
Waiting for Bedrock node to initialize...

Here is my .env file:

`###############################################################################
#                                ↓ REQUIRED ↓                                 #
###############################################################################

# Network to run the node on ("op-mainnet" or "op-sepolia")
NETWORK_NAME=op-mainnet

# Type of node to run ("full" or "archive"), note that "archive" is 10x bigger
NODE_TYPE=full

###############################################################################
#                            ↓ REQUIRED (BEDROCK) ↓                           #
###############################################################################

# Where to get the Bedrock database ("download" or "migration"), see README
BEDROCK_SOURCE=download

# L1 node that the op-node (Bedrock) will get chain data from
OP_NODE__RPC_ENDPOINT=https://eth-mainnet.g.alchemy.com/v2/xxxxxxxxxxxx

# L1 beacon endpoint, you can setup your own or use Quicknode
OP_NODE__L1_BEACON=https://beaconcha-rpc.xxxxxxxxi.io

# Type of RPC that op-node is connected to, see README
OP_NODE__RPC_TYPE=basic

# Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://opt-mainnet.g.alchemy.com/v2/xxxxxxx
###############################################################################
#                            ↓ OPTIONAL (BEDROCK) ↓                           #
###############################################################################

# Optional provider to serve legacy RPC requests, see README
OP_GETH__HISTORICAL_RPC=https://mainnet.optimism.io

###############################################################################
#                                ↓ OPTIONAL ↓                                 #
###############################################################################

# Feel free to customize your image tag if you want, uses "latest" by default
# See here for all available images: https://hub.docker.com/u/ethereumoptimism
IMAGE_TAG__L2GETH=
IMAGE_TAG__DTL=
IMAGE_TAG__HEALTCHECK=
IMAGE_TAG__PROMETHEUS=
IMAGE_TAG__GRAFANA=
IMAGE_TAG__INFLUXDB=
IMAGE_TAG__OP_GETH=
IMAGE_TAG__OP_NODE=

# Exposed server ports (must be unique)
# See docker-compose.yml for default values
PORT__L2GETH_HTTP=
PORT__L2GETH_WS=
PORT__DTL=
PORT__HEALTHCHECK_METRICS=
PORT__PROMETHEUS=
PORT__GRAFANA=
PORT__INFLUXDB=
PORT__TORRENT_UI=
PORT__TORRENT=
PORT__OP_GETH_HTTP=
PORT__OP_GETH_WS=
PORT__OP_NODE_P2P=`

**Comment by wetezos** [comment]
` docker logs simple-optimism-node-bedrock-init-1 -f
posix           off
privileged      off
verbose         off
vi              off
xtrace          off
Bedrock node needs to be initialized...
Initializing via download...
Fetching download link...
Downloading bedrock.tar...
./scripts/utils.sh: line 35: aria2c: command not found`

**Comment by Chomtana** [comment]
Do you start with --build flag?

```
docker compose up -d --build
```

If you previously have launched a node it may cache old image unless you have supplied --build

**Comment by wetezos** [comment]
close
