### ISSUE TITLE
./progress.sh: line 9: cast: command not found

### ISSUE THREAD

**Issue by dholliday** [smartcontracts/simple-optimism-node#130]
Running a node in Ubuntu 20.04 and getting cast: command not found error. Any ideas?

> ./progress.sh
./progress.sh: line 9: cast: command not found
Chain ID:
Please wait
./progress.sh: line 13: [: -eq: unary operator expected
./progress.sh: line 18: [: -eq: unary operator expected
./progress.sh: line 23: [: -eq: unary operator expected
./progress.sh: line 27: cast: command not found
./progress.sh: line 27: cast: command not found
expr: non-integer argument
Blocks per minute:
./progress.sh: line 33: [: -eq: unary operator expected
./progress.sh: line 40: cast: command not found
expr: syntax error: missing argument after ‘/’
expr: syntax error: unexpected argument ‘60’
./progress.sh: line 45: [: -le: unary operator expected
./progress.sh: line 49: [: -gt: unary operator expected
./progress.sh: line 53: [: -gt: unary operator expected

**Comment by Chomtana** [comment]
You need to run `curl -L https://foundry.paradigm.xyz | bash` and `source .bashrc` to install cast before running progress.sh

https://book.getfoundry.sh/getting-started/installation

**Comment by dholliday** [comment]
Perfect. Solved it thanks! :)
