### ISSUE TITLE
Upcoming features notice

### ISSUE THREAD

**Issue by Chomtana** [smartcontracts/simple-optimism-node#131]
There may be a breaking change coming shortly
* [ ] Beacon Archiver
* [x] Snap Sync
* [x] Base support

**Comment by hdiass** [comment]
How to initialize for snapsync ?

**Comment by Chomtana** [comment]
Snap sync is now a default option for simple-optimism-node. You can enter your L1 endpoints and start the docker compose as usual and it should start snap sync within 30 min.

Or you can explicitly set `OP_GETH__SYNCMODE=snap` in .env

**Comment by hdiass** [comment]
If i don't use a snapshot to initlialize the op-geth the op-node fails 
```
failed to setup: unable to create the rollup node: failed to init L2: incorrect L2 RPC chain id 1, expected 10
```

**Comment by Chomtana** [comment]
Hmm that's weird. Are you sure you're on the latest simple-optimism-node (git pull)?

**Comment by Chomtana** [comment]
Also don't forget to add --build when restarting the docker compose if you have run simple-optimism-node before. Otherwise, it won't update.

```
docker compose pull
docker compose up -d --build
```

**Comment by Chomtana** [comment]
Have you passed

```
--op-network=op-mainnet
```

To op-geth? That's what allow it to load op-mainnet genesis

**Comment by hdiass** [comment]
Nope, that was probably the problem. Will test. Another question how long it takes to snap sync this days ?
