### ISSUE TITLE
sync stopped

### ISSUE THREAD

**Issue by BoogalooLi** [smartcontracts/simple-optimism-node#132]
Node stuck at 0x6db5b20/115039008. Here's the version and logs of the config:
op-geth:v1.101308.1
op-node:v1.6.1
bedrock-init logs

> simple-optimism-node-bedrock-init-1  | allexport      	off
> simple-optimism-node-bedrock-init-1  | braceexpand    	on
> simple-optimism-node-bedrock-init-1  | emacs          	off
> simple-optimism-node-bedrock-init-1  | errexit        	on
> simple-optimism-node-bedrock-init-1  | errtrace       	off
> simple-optimism-node-bedrock-init-1  | functrace      	off
> simple-optimism-node-bedrock-init-1  | hashall        	on
> simple-optimism-node-bedrock-init-1  | histexpand     	off
> simple-optimism-node-bedrock-init-1  | history        	off
> simple-optimism-node-bedrock-init-1  | ignoreeof      	off
> simple-optimism-node-bedrock-init-1  | interactive-comments	on
> simple-optimism-node-bedrock-init-1  | keyword        	off
> simple-optimism-node-bedrock-init-1  | monitor        	off
> simple-optimism-node-bedrock-init-1  | noclobber      	off
> simple-optimism-node-bedrock-init-1  | noexec         	off
> simple-optimism-node-bedrock-init-1  | noglob         	off
> simple-optimism-node-bedrock-init-1  | nolog          	off
> simple-optimism-node-bedrock-init-1  | notify         	off
> simple-optimism-node-bedrock-init-1  | nounset        	off
> simple-optimism-node-bedrock-init-1  | onecmd         	off
> simple-optimism-node-bedrock-init-1  | physical       	off
> simple-optimism-node-bedrock-init-1  | pipefail       	off
> simple-optimism-node-bedrock-init-1  | posix          	off
> simple-optimism-node-bedrock-init-1  | privileged     	off
> simple-optimism-node-bedrock-init-1  | verbose        	off
> simple-optimism-node-bedrock-init-1  | vi             	off
> simple-optimism-node-bedrock-init-1  | xtrace         	off
> simple-optimism-node-bedrock-init-1  | Bedrock node already initialized

op-geth logs

> simple-optimism-node-op-geth-1  | errexit         on
> simple-optimism-node-op-geth-1  | noglob          off
> simple-optimism-node-op-geth-1  | ignoreeof       off
> simple-optimism-node-op-geth-1  | monitor         off
> simple-optimism-node-op-geth-1  | noexec          off
> simple-optimism-node-op-geth-1  | xtrace          off
> simple-optimism-node-op-geth-1  | verbose         off
> simple-optimism-node-op-geth-1  | noclobber       off
> simple-optimism-node-op-geth-1  | allexport       off
> simple-optimism-node-op-geth-1  | notify          off
> simple-optimism-node-op-geth-1  | nounset         off
> simple-optimism-node-op-geth-1  | errtrace        off
> simple-optimism-node-op-geth-1  | vi              off
> simple-optimism-node-op-geth-1  | pipefail        off
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.283] Starting geth on an OP network...        network=op-mainnet
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.283] Bumping default cache on mainnet         provided=1024 updated=4096 network=op-mainnet
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.283] Enabling metrics collection
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.284] Enabling metrics export to InfluxDB
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.285] Maximum peer count                       ETH=0 total=0
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.286] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.289] Set global gas cap                       cap=50,000,000
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.290] Initializing the KZG library             backend=gokzg
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.314] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.679] Using leveldb as the backing database
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:03.679] Allocated cache and file handles         database=/geth/geth/chaindata cache=2.00GiB handles=524,288
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:06.276] Using LevelDB as the backing database
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:06.276] Found legacy ancient chain path          location=/geth/geth/chaindata/ancient
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:06.349] Opened ancient database                  database=/geth/geth/chaindata/ancient readonly=false
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:06.387] State scheme set to already existing     scheme=hash
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] ---------------------------------------------------------------------------------------------------------------------------------------------------------
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Chain ID:  10 (OP-Mainnet)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Consensus: Optimism
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Pre-Merge hard forks (block based):
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Homestead:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/homestead.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Tangerine Whistle (EIP 150): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/tangerine-whistle.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Spurious Dragon/1 (EIP 155): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Spurious Dragon/2 (EIP 158): #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/spurious-dragon.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Byzantium:                   #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/byzantium.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Constantinople:              #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/constantinople.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Petersburg:                  #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/petersburg.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Istanbul:                    #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/istanbul.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Muir Glacier:                #0        (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/muir-glacier.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Berlin:                      #3950000  (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/berlin.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - London:                      #105235063 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/london.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Arrow Glacier:               #105235063 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/arrow-glacier.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Gray Glacier:                #105235063 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/gray-glacier.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Merge configured:
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Network known to be merged: true
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Total terminal difficulty:  0
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Merge netsplit block:       #105235063
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Post-Merge hard forks (timestamp based):
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Shanghai:                    @1704992401 (https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md)
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Cancun:                      @1710781201
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Regolith:                    @0         
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Canyon:                      @1704992401
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365]  - Ecotone:                     @1710781201
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] ---------------------------------------------------------------------------------------------------------------------------------------------------------
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] 
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Loaded most recent local block           number=115,039,008 hash=22a9ed..85a83a td=0 age=1mo1w3d
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.365] Loaded most recent local finalized block number=115,038,563 hash=f0f4d6..5c6f28 td=0 age=1mo1w3d
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.406] Initialising Ethereum protocol           network=10         dbversion=8
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.406] Initialized transaction indexer          limit=2,350,000
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.406] Loaded local transaction journal         transactions=0 dropped=0
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.406] Regenerated local transaction journal    transactions=0 accounts=0
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.407] Chain post-merge, sync via beacon client
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.407] Gasprice oracle is ignoring threshold set threshold=2
> simple-optimism-node-op-geth-1  | WARN [02-29|07:51:07.407] Engine API enabled                       protocol=eth
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.407] Starting peer-to-peer node               instance=Geth/v0.1.0-unstable-f33198a0/linux-amd64/go1.21.7
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.436] IPC endpoint opened                      url=/geth/geth.ipc
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.436] Loaded JWT secret file                   path=/shared/jwt.txt crc32=0x413f61ff
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] HTTP server started                      endpoint=[::]:8545 auth=false prefix= cors=* vhosts=*
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] WebSocket enabled                        url=ws://[::]:8546
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] WebSocket enabled                        url=ws://[::]:8551
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] HTTP server started                      endpoint=[::]:8551 auth=true  prefix= cors=localhost vhosts=*
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] New local node record                    seq=1,694,117,146,191 id=46e19b80538f7408 ip=127.0.0.1 udp=0 tcp=30303
> simple-optimism-node-op-geth-1  | INFO [02-29|07:51:07.437] Started P2P networking                   self="enode://66802ca81fe651374ea229d3e23674a6d367049b1ec0ebc46729a4d36d09b894c2bb64d93ffc1b66074a8010c961430e5298298e5cd47a0b07d05462e06754fb@127.0.0.1:30303?discport=0"

op-node logs

> simple-optimism-node-op-node-1  | errexit         on
> simple-optimism-node-op-node-1  | noglob          off
> simple-optimism-node-op-node-1  | ignoreeof       off
> simple-optimism-node-op-node-1  | monitor         off
> simple-optimism-node-op-node-1  | noexec          off
> simple-optimism-node-op-node-1  | xtrace          off
> simple-optimism-node-op-node-1  | verbose         off
> simple-optimism-node-op-node-1  | noclobber       off
> simple-optimism-node-op-node-1  | allexport       off
> simple-optimism-node-op-node-1  | notify          off
> simple-optimism-node-op-node-1  | nounset         off
> simple-optimism-node-op-node-1  | errtrace        off
> simple-optimism-node-op-node-1  | vi              off
> simple-optimism-node-op-node-1  | pipefail        off
> simple-optimism-node-op-node-1  | t=2024-02-29T07:58:51+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE__RPC_ENDPOINT=https://eth.llamarpc.com"
> simple-optimism-node-op-node-1  | t=2024-02-29T07:58:51+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE__L1_BEACON="
> simple-optimism-node-op-node-1  | t=2024-02-29T07:58:51+0000 lvl=warn msg="Unknown env var" prefix=OP_NODE env_var="OP_NODE__RPC_TYPE=basic"
> simple-optimism-node-op-node-1  | t=2024-02-29T07:58:51+0000 lvl=crit msg="Application failed" message="failed to setup: unable to create the rollup node config: misconfigured L1 Beacon API endpoint: expected L1 Beacon API endpoint, but got none"

.env file

> #                            ↓ OPTIONAL (BEDROCK) ↓                           #
> ###############################################################################
> 
> # Optional provider to serve legacy RPC requests, see README
> OP_GETH__HISTORICAL_RPC=https://mainnet.optimism.io
> 
> ###############################################################################
> #                                ↓ OPTIONAL ↓                                 #
> ###############################################################################
> 
> # Feel free to customize your image tag if you want, uses "latest" by default
> # See here for all available images: https://hub.docker.com/u/ethereumoptimism
> IMAGE_TAG__L2GETH=
> IMAGE_TAG__DTL=
> IMAGE_TAG__HEALTCHECK=
> IMAGE_TAG__PROMETHEUS=
> IMAGE_TAG__GRAFANA=
> IMAGE_TAG__INFLUXDB=
> IMAGE_TAG__OP_GETH=
> IMAGE_TAG__OP_NODE=
> 
> # Exposed server ports (must be unique)
> # See docker-compose.yml for default values
> PORT__L2GETH_HTTP=
> PORT__L2GETH_WS=
> PORT__DTL=
> PORT__HEALTHCHECK_METRICS=

**Comment by Chomtana** [comment]
Hi, try upgrading to v1.7.1 and also setting up OP_NODE__L1_BEACON too (You can use Quicknode for this)

https://github.com/smartcontracts/simple-optimism-node/releases/tag/v1.7.1

**Comment by BoogalooLi** [comment]
Thank you. I will try it.
