### ISSUE TITLE
Sync stopped at 117387811

### ISSUE THREAD

**Issue by lixiubao4967** [smartcontracts/simple-optimism-node#135]
My node suddenly became out of sync when the block height was 117387811. I don’t know what caused the problem. The health check error is as follows:
healthcheck-1  | {"level":50,"time":1710494634719,"extra":{"message":"Cannot read properties of null (reading 'number')","stack":"TypeError: Cannot read properties of null (reading 'number')\n    at HealthcheckService.main (/opt/optimism/packages/replica-healthcheck/src/service.ts:144:32)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Timeout.doLoop [as _onTimeout] (/opt/optimism/packages/common-ts/src/base-service/base-service-v2.ts:420:11)"},"msg":"caught an unhandled exception"}

**Comment by lixiubao4967** [comment]
my node docker config is as follows:
> sudo docker ps
CONTAINER ID   IMAGE                                                                 COMMAND                  CREATED          STATUS          PORTS                                                                                                        NAMES
579ca7e67773   us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101308.1   "/scripts/start-op-g…"   15 minutes ago   Up 15 minutes   30303/tcp, 30303/udp, 0.0.0.0:8332->8545/tcp, :::8332->8545/tcp, 0.0.0.0:9994->8546/tcp, :::9994->8546/tcp   simple-optimism-node-op-geth-1
e0e644afec4e   prom/prometheus:latest                                                "/bin/prometheus --c…"   15 minutes ago   Up 15 minutes   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                                    simple-optimism-node-prometheus-1
f5390ea5fafa   grafana/grafana:9.3.0                                                 "/run.sh"                15 minutes ago   Up 15 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                    simple-optimism-node-grafana-1
54b7186e8747   influxdb:1.8                                                          "/entrypoint.sh infl…"   15 minutes ago   Up 15 minutes   0.0.0.0:8086->8086/tcp, :::8086->8086/tcp                                                                    simple-optimism-node-influxdb-1
f07a5309296e   ethereumoptimism/replica-healthcheck:latest                           "pnpm run start"         15 minutes ago   Up 15 minutes   0.0.0.0:7300->7300/tcp, :::7300->7300/tcp                                                                    simple-optimism-node-healthcheck-1
79e7240173db   us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.7.1        "/scripts/start-op-n…"   15 minutes ago   Up 15 minutes   0.0.0.0:9003->9003/tcp, 0.0.0.0:9003->9003/udp, :::9003->9003/tcp, :::9003->9003/udp                         simple-optimism-node-op-node-1

**Comment by lixiubao4967** [comment]
I've upgraded to the latest version now, but it still won't update.
[2024-03-15 19:00:03] > sudo docker ps
CONTAINER ID   IMAGE                                                                 COMMAND                  CREATED         STATUS         PORTS                                                                                                                                                                                                      NAMES
2f3b312606a6   influxdb:1.8                                                          "/entrypoint.sh infl…"   3 minutes ago   Up 3 minutes   0.0.0.0:8086->8086/tcp, :::8086->8086/tcp                                                                                                                                                                  simple-optimism-node-influxdb-1
e90d9dc09612   prom/prometheus:latest                                                "/bin/prometheus --c…"   3 minutes ago   Up 3 minutes   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                                                                                                                                                                  simple-optimism-node-prometheus-1
b98325aa718a   us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101308.2   "/scripts/start-op-g…"   3 minutes ago   Up 3 minutes   30303/tcp, 30303/udp, 0.0.0.0:39393->39393/tcp, 0.0.0.0:39393->39393/udp, :::39393->39393/tcp, :::39393->39393/udp, 0.0.0.0:8332->8545/tcp, :::8332->8545/tcp, 0.0.0.0:9994->8546/tcp, :::9994->8546/tcp   simple-optimism-node-op-geth-1
eb1b0e0ef893   us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.7.1        "/scripts/start-op-n…"   3 minutes ago   Up 3 minutes   0.0.0.0:9003->9003/tcp, 0.0.0.0:9003->9003/udp, :::9003->9003/tcp, :::9003->9003/udp                                                                                                                       simple-optimism-node-op-node-1
e922c2b04614   grafana/grafana:9.3.0                                                 "/run.sh"                3 minutes ago   Up 3 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                                                                                                  simple-optimism-node-grafana-1
5ed8e83a4a83   ethereumoptimism/replica-healthcheck:latest                           "pnpm run start"         3 minutes ago   Up 3 minutes   0.0.0.0:7300->7300/tcp, :::7300->7300/tcp                                                                                                                                                                  simple-optimism-node-healthcheck-1
okj-admin@okj-op-node-a01 [~/simple-optimism-node]
[2024-03-15 19:00:05] > sudo docker images
REPOSITORY                                                TAG           IMAGE ID       CREATED         SIZE
influxdb                                                  1.8           9edd2540ada1   3 days ago      307MB
simple-optimism-node-bedrock-init                         latest        559aaca02d05   8 days ago      1.12GB
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node   v1.7.1        e1ba0c36ffa0   8 days ago      73.2MB
<none>                                                    <none>        839c7234ab67   11 days ago     1.13GB
prom/prometheus                                           latest        6a5ddde754b6   2 weeks ago     254MB
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth   v1.101308.2   da6e8ea90d62   2 weeks ago     75MB
us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth   v1.101308.1   9111104177dc   4 weeks ago     75MB
influxdb                                                  <none>        52538bd7e50e   4 weeks ago     307MB
ethereumoptimism/replica-healthcheck                      latest        b0a2d1a00d50   7 months ago    3.91GB
ethereumoptimism/l2geth                                   latest        534c8f6ace5a   14 months ago   41.6MB
grafana/grafana                                           9.3.0         b608ef7e2f5b   15 months ago   315MB

**Comment by Chomtana** [comment]
Check if you have set `OP_NODE__L1_BEACON=<YourBeaconNodeEndpoint>` in the .env file before restarting the docker-compose

```
docker compose pull
docker compose up -d --build
```

If it's still not working, I advise you to wipe the volume and resync. It wouldn't take more than 1 day as snap sync has been implemented.

```
docker compose down -v
docker compose pull
docker compose up -d --build
```
