### ISSUE TITLE
How to Prune with Simple-Optimism-Node

### ISSUE THREAD

**Issue by mhaddad9** [smartcontracts/simple-optimism-node#139]
Finally got my node to sync and it is using all but 100GB on my 2TB drive. I tried reading the documentation for Geth on pruning and it's fairly confusing - particularly how it would apply here. Is there a flag I can set in the start-op-geth.sh script to initiate pruning? Much appreciated!

**Comment by Chomtana** [comment]
From @sbvegan 

> I have confirmed that offline pruing works in the same way as geth. So you can prune op-geth. You can refer to these geth docs as a reference: https://geth.ethereum.org/docs/fundamentals/pruning

However, users who follow this guide report database corruption after pruning. Probably, it isn't designed for Optimism.

https://github.com/ethereum-optimism/developers/discussions/185
