### ISSUE TITLE
I reinstalled the op-node, but it is out of sync.

### ISSUE THREAD

**Issue by lixiubao4967** [smartcontracts/simple-optimism-node#149]
My new node environment configuration is as follows:
okj-admin@okj-op-node-a01:/data/opnode/simple-optimism-node$ grep -vE '^\s*#|^\s*$' .env
NETWORK_NAME=op-mainnet
NODE_TYPE=full
BEDROCK_SOURCE=download
OP_NODE__RPC_ENDPOINT=http://35.78.x.x:7001
OP_NODE__L1_BEACON=http://35.78.x.x:3500
OP_NODE__RPC_TYPE=basic
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://mainnet.optimism.io
OP_GETH__HISTORICAL_RPC=https://mainnet.optimism.io
OP_GETH__SYNCMODE=snap
IMAGE_TAG__L2GETH=
IMAGE_TAG__DTL=
IMAGE_TAG__HEALTCHECK=
IMAGE_TAG__PROMETHEUS=
IMAGE_TAG__GRAFANA=
IMAGE_TAG__INFLUXDB=
IMAGE_TAG__OP_GETH=
IMAGE_TAG__OP_NODE=
PORT__L2GETH_HTTP=
PORT__L2GETH_WS=
PORT__DTL=
PORT__HEALTHCHECK_METRICS=
PORT__PROMETHEUS=
PORT__GRAFANA=
PORT__INFLUXDB=
PORT__TORRENT_UI=
PORT__TORRENT=
PORT__OP_GETH_HTTP=
PORT__OP_GETH_WS=
PORT__OP_GETH_P2P=
PORT__OP_NODE_P2P=
PORT__OP_NODE_HTTP=

My new node sync log is as follows:
![image](https://github.com/smartcontracts/simple-optimism-node/assets/79096302/cd2dcc58-4d81-4a21-a38a-1a9ba11ceb4e)

**Comment by Chomtana** [comment]
Can you post log of op-node and op-geth ?

**Comment by lixiubao4967** [comment]
![image](https://github.com/smartcontracts/simple-optimism-node/assets/79096302/65121539-d201-4d59-a252-ea1afb862631)

Sorry, I checked again today and somehow the synchronization was completed.

**Comment by lixiubao4967** [comment]
But I have another newly created node, which is not synchronized now. Do I need to wait for some time?

log is as following:
![image](https://github.com/smartcontracts/simple-optimism-node/assets/79096302/f416376a-922b-408c-8af8-70b4ba728611)

configuration is as following:
![image](https://github.com/smartcontracts/simple-optimism-node/assets/79096302/4429927b-c9b1-4eaf-898c-7a0920289bed)

**Comment by Chomtana** [comment]
It looks like it's snap syncing. It should take no more than 1 day
