### ISSUE TITLE
Incorrect RPC Query response from eth_getBlockByNumber

### ISSUE THREAD

**Issue by bmalepaty** [smartcontracts/simple-optimism-node#15]
We have setup the Optimism Node using the Infura Provider.

.env:
`
//Network to run the node on ("mainnet" or "kovan")
NETWORK_NAME=mainnet

//Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://optimism-mainnet.infura.io/v3/<MY_PROJECT_ID>
//L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=https://mainnet.infura.io/v3/<MY_PROJECT_ID>
//L1 node to get chain data from
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://mainnet.infura.io/v3/<MY_PROJECT_ID>
`

Nodes were syncing successfully.
# cURL Query:
`
curl -X POST \
-H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 17, "method": "eth_getBlockByNumber", "params": ["0x1", true]}' \
"https://optimism-goerli.infura.io/v3/<MY_PROJECT_ID"`

# QUERY RESPONSE:
`{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "difficulty": "0x2",
    "extraData": "0xd98301090a846765746889676f312e31352e3133856c696e7578000000000000844432a0becc67a5ff047d22b87f3e7f4bf40c875a10976cdc2c4bfe743dd3f74a7a6a5e22e90187d42f53cb6d367d57b6710555cfc0e94ae088bd09239c0b5300",
    "gasLimit": "0xe4e1c0",
    "gasUsed": "0x24e97",
    "hash": "0x15d55041e8f7b0d1f303b6d4cefe2d2efc257d67acd9f17307261a8f7d786e0e",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000001000000000000000800080000000000000000000000800000000000000000000001240000000020024000000000008000000000000000000000000000000000000000100000000020000400000000000020800000000000000400000000018000000000000200000000000000000000000000001800000000000000020000000000000000080000000000000000000000000000000200000000000000000000000000000000002000000000000000000000000080002110000000000000000000020001000000000000000000000000000000000000000000000000000000008000000",
    "miner": "0x0000000000000000000000000000000000000000",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x0000000000000000",
    "number": "0x1",
    "parentHash": "0xc1fc15cd51159b1f1e5cbc4b82e85c1447ddfa33c52cf1d98d14fba0d6354be1",
    "receiptsRoot": "0x1077772098617e7ad0ca5ea6f237ba126df503cca310bb3074f362f13360d2db",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0x42c",
    "stateRoot": "0x66d870dd004e61eb6e64e126155c99146139ac8be229500b872f0db57bb997ca",
    "timestamp": "0x62a209e3",
    "totalDifficulty": "0x3",
    "transactions": [
      "0x7334ddc1f6beaf66892c25cffdecec275cdfabaf4def047f0c3ce20e6f6483e8"
    ],
    "transactionsRoot": "0xeb1aff3d8e7d685c6902bc04b9b5b816498fb262ce5a404b0cc835737bdf97e4",
    "uncles": []
  }
}`

The transaction hash (0x7334ddc1f6beaf66892c25cffdecec275cdfabaf4def047f0c3ce20e6f6483e8) present in the response for Block Number 1 (0x1) was neither found in the Optimism Explorer not the Ethereum Explorer. 
The block hash (0x15d55041e8f7b0d1f303b6d4cefe2d2efc257d67acd9f17307261a8f7d786e0e) also does not match the one present on the Optimism Explorer.
Can you please help what this transaction hash denotes?

**Comment by smartcontracts** [comment]
Appears to be comparing a Goerli result to a mainnet result.
