### ISSUE TITLE
Incorrect RPC Response while using Alchemy Node Provider

### ISSUE THREAD

**Issue by bmalepaty** [smartcontracts/simple-optimism-node#16]
When querying for block/transaction details using Alchemy Node Provider, the value for L1BlockNumber from RPC response does not match with one displayed on Explorer.

.env
`//Network to run the node on ("mainnet" or "kovan")
NETWORK_NAME=mainnet
//Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://opt-mainnet.g.alchemy.com/v2/<API_KEY>
//L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=https://eth-mainnet.alchemyapi.io/v2/<API_KEY>
//L1 node to get chain data from
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=https://eth-mainnet.alchemyapi.io/v2/<API_KEY>
`

cURL Query:
```
curl https://opt-mainnet.g.alchemy.com/v2/K7AdDANFuuEL2YribeS6PDgm8pRX5l21 \
-X POST \
-H "Content-Type: application/json" \
-d'{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x815804d4fdf5786ff955658f21191fcdf34c7ad437d0d5f517ff83b4a97325cf"],"id":0}'
```

cURL Response:
`{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "hash": "0x815804d4fdf5786ff955658f21191fcdf34c7ad437d0d5f517ff83b4a97325cf",
    "blockHash": "0x830e63c03eadc3108bf8bb7cc35cb51fd35350b73dc11a9a9cdbf2a8f3c33aad",
    "blockNumber": "0xdb58de",
    "from": "0xc6c3e4bbcdc719e7b5793a31a36937f729605c33",
    "gas": "0x4f294",
    "gasPrice": "0xf4240",
    "index": "0xdb58dd",
    "input": "0x415565b0000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000a1045f00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000460000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000060000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000012556e6973776170563300000000000000000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000a1045f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002b42000000000000000000000000000000000000060001f47f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000020000000000000000000000004200000000000000000000000000000000000006000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000000869584cd0000000000000000000000003ce37278de6388532c3949ce4e886f365b14fb5600000000000000000000000000000000000000000000001f4a14c6b462ce88f1",
    "l1BlockNumber": "0xe6ea7d",
    "l1Timestamp": "0x62ce8900",
    "l1TxOrigin": null,
    "nonce": "0x5a",
    "queueIndex": null,
    "queueOrigin": "sequencer",
    "r": "0x9ee8e6c2f2916d0cf16cbe3b1ae1d58b39f7edfdc740b39d2b72882ab6867393",
    "rawTransaction": "0xf907145a830f42408304f29494def1abe32c034e558cdd535791643c58a13acc10872386f26fc10000b906a8415565b0000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000a1045f00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000460000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000042000000000000000000000000000000000000060000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000002c000000000000000000000000000000000000000000000000000000000000002a0000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000012556e6973776170563300000000000000000000000000000000000000000000000000000000000000002386f26fc100000000000000000000000000000000000000000000000000000000000000a1045f000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000e592427a0aece92de3edee1f18e0157c058615640000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002b42000000000000000000000000000000000000060001f47f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000020000000000000000000000004200000000000000000000000000000000000006000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000000869584cd0000000000000000000000003ce37278de6388532c3949ce4e886f365b14fb5600000000000000000000000000000000000000000000001f4a14c6b462ce88f138a09ee8e6c2f2916d0cf16cbe3b1ae1d58b39f7edfdc740b39d2b72882ab6867393a00194b4bf431dc430facd52bea4e1e00f5609cb43a3ab12d7b6951e7959c0105f",
    "s": "0x194b4bf431dc430facd52bea4e1e00f5609cb43a3ab12d7b6951e7959c0105f",
    "to": "0xdef1abe32c034e558cdd535791643c58a13acc10",
    "transactionIndex": "0x0",
    "v": "0x38",
    "value": "0x2386f26fc10000"
  }
}`

In the above response l1BlockNumber is '0xe6ea7d' which is 15133309. But explorer shows the L1BlockNumber for this transaction to be 15133361
![image](https://user-images.githubusercontent.com/77955726/178986345-547f79a2-8807-442c-a628-b4eee7d1af15.png)
![image](https://user-images.githubusercontent.com/77955726/178986467-f8354a83-a4b8-47a9-aa58-ad89e8161f6d.png)

**Comment by smartcontracts** [comment]
This is probably an issue for the primary monorepo, I recommend opening an issue there if you still have concerns here
