### ISSUE TITLE
When I run it, the following error appears, how can I fix it?

### ISSUE THREAD

**Issue by guanzhenxing** [smartcontracts/simple-optimism-node#17]
When I run it, the following error appears, how can I fix it?

The Error is “You cannot query logs for more than 100000 blocks at once.” 

![error](https://user-images.githubusercontent.com/3087325/183227593-02e231ab-86e1-40fd-94ff-d7cf0e6b8635.jpeg)

**Comment by smartcontracts** [comment]
Hi, sorry for the late response here. I believe this is an upstream bug in a service called the `data-transport-layer` which is being caused by a less-than-optimal log query. You can usually resolve this issue by using an L1 provider like Infura or Alchemy.
