### ISSUE TITLE
subscribing to newHeaders event is fiered once every few minutes instead of every block

### ISSUE THREAD

**Issue by ohadgk** [smartcontracts/simple-optimism-node#23]
I was managed to get the node synced (afetr a lot of struggling), but now it seems like it dosent work as expected.

When I subscribe to "newHeaders" event with web3/ethers the event is fiered only once every few minutes, with around few hundred blocks.

looking at the l2geth logs, I can see the node is reciving new blocks in batches instead of every block. It is also shown in the grafana:

<img width="824" alt="Screenshot_20221029_125141" src="https://user-images.githubusercontent.com/10048484/198830091-cc5a903e-0aa0-4e5d-ab5e-c30128d852ce.png">

is that regular behaviour? or did i mess something up?

**Comment by smartcontracts** [comment]
This is expected behavior when syncing the Legacy node from L1. When we move to Bedrock it will behave more like you expect. You can also sync from L2 if you want the expected behavior now, at the cost of trusting the node that you are syncing from.
