### ISSUE TITLE
Use L1 data-transport-layer  have error

### ISSUE THREAD

**Issue by zhy827827** [smartcontracts/simple-optimism-node#28]
.env config file:
SYNC_SOURCE=l1 
FAULT_DETECTOR__L1_RPC_PROVIDER=http://13.213.5.*:8545
DATA_TRANSPORT_LAYER__RPC_ENDPOINT=http://13.213.5.*:8545

ethereumoptimism/data-transport-layer:latest have error:

dtl_1             | {"level":50,"time":1670923715489,"extra":{"message":"TypeError: Cannot read properties of null (reading 'from')","stack":"TypeError: Cannot read properties of null (reading 'from')\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:27:38)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:277:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:156:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}

How can I solve this problem？？ optimism is the chain that takes me the most time!! 😭😭😭😭 
Always unable to provide services。

**Comment by smartcontracts** [comment]
This usually means there's an issue with your L1 RPC endpoint. Are you running Geth? Have you confirmed that the L1 RPC is working as expected?

**Comment by dandavid3000** [comment]
Hi ! 
I also have an issue with syncing from L1. It's not from the dtl but from. default detector and healthcheck. Somehow they don't work at all. I changed multi L1 RPCs and can confirm they worked normally.

```
simple-optimism-node-healthcheck-1     | {"level":50,"time":1670967611269,"msg":"target client not connected"}
simple-optimism-node-healthcheck-1     | {"level":50,"time":1670967616272,"msg":"target client not connected"}
simple-optimism-node-healthcheck-1     | {"level":30,"time":1670967617218,"log":"172.18.0.8 - GET /metrics HTTP/1.1 200 - - 6.397 ms\n","msg":"server log"}
simple-optimism-node-healthcheck-1     | {"level":50,"time":1670967621278,"msg":"target client not connected"}
simple-optimism-node-healthcheck-1     | {"level":50,"time":1670967626284,"msg":"target client not connected"}
^[^Gsimple-optimism-node-healthcheck-1     | {"level":50,"time":1670967631289,"msg":"target client not connected"}
simple-optimism-node-dtl-1             | {"level":30,"time":1670967631827,"eventName":"SequencerBatchAppended","numEvents":41,"durationMs":46970,"msg":"Processed events"}
simple-optimism-node-healthcheck-1     | {"level":30,"time":1670967632218,"log":"172.18.0.8 - GET /metrics HTTP/1.1 200 - - 6.374 ms\n","msg":"server log"}
simple-optimism-node-fault-detector-1  | 
simple-optimism-node-fault-detector-1  | > @eth-optimism/fault-detector@0.4.0 start
simple-optimism-node-fault-detector-1  | > ts-node ./src/service.ts
simple-optimism-node-fault-detector-1  | 
simple-optimism-node-fault-detector-1  | {"level":30,"time":1670967635114,"msg":"starting app server"}
simple-optimism-node-fault-detector-1  | {"level":30,"time":1670967635130,"port":7300,"hostname":"0.0.0.0","msg":"app server started"}
simple-optimism-node-fault-detector-1  | {"level":30,"time":1670967635130,"msg":"initializing service"}
simple-optimism-node-fault-detector-1  | /opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269
simple-optimism-node-fault-detector-1  |         const error: any = new Error(message);
simple-optimism-node-fault-detector-1  |                            ^
simple-optimism-node-fault-detector-1  | Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.1)
simple-optimism-node-fault-detector-1  |     at Logger.makeError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
simple-optimism-node-fault-detector-1  |     at Logger.throwError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
simple-optimism-node-fault-detector-1  |     at JsonRpcProvider.<anonymous> (/opt/optimism/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
simple-optimism-node-fault-detector-1  |     at step (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
simple-optimism-node-fault-detector-1  |     at Object.throw (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
simple-optimism-node-fault-detector-1  |     at rejected (/opt/optimism/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
simple-optimism-node-fault-detector-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
simple-optimism-node-fault-detector-1  |   reason: 'could not detect network',
simple-optimism-node-fault-detector-1  |   code: 'NETWORK_ERROR',
simple-optimism-node-fault-detector-1  |   event: 'noNetwork'
simple-optimism-node-fault-detector-1  | }
simple-optimism-node-fault-detector-1  | npm ERR! Lifecycle script `start` failed with error: 
simple-optimism-node-fault-detector-1  | npm ERR! Error: command failed 
simple-optimism-node-fault-detector-1  | npm ERR!   in workspace: @eth-optimism/fault-detector@0.4.0 
simple-optimism-node-fault-detector-1  | npm ERR!   at location: /opt/optimism/packages/fault-detector 
simple-optimism-node-fault-detector-1 exited with code 1

```

p/s : L2 syncing work normally
Do you have any suggestions ?
Thanks

**Comment by zhy827827** [comment]
yes, i running Geth is the latest version. All other chains are connected to geth.for example: polygon ，There is no problem。

I really don't know how to set Optimism to synchronize from L1
@smartcontracts 

If I synchronize from l2(with alchemy), an error will be reported after the synchronization is completed：
Synchronizing unconfirmed transactions from Layer 2 (Optimism)

**Comment by smartcontracts** [comment]
Ah fault detector and healthcheck will report errors when the L2 client isn't open to requests yet. I need to fix that...
