### ISSUE TITLE
Running archive node : stuck in error state after restart

### ISSUE THREAD

**Issue by raffiegang** [smartcontracts/simple-optimism-node#37]
The last weeks I've been steadily building the archive node; however at about 90% my machine crashed. After restarting it seems to be stuck in an error state.

```
simple-optimism-node-dtl-1  | {"level":50,"time":1673877945647,"extra":{"message":"Error: Well, this really shouldn't happen. A SequencerBatchAppended event doesn't have a corresponding TransactionBatchAppended event.","stack":"Error: Well, this really shouldn't happen. A SequencerBatchAppended event doesn't have a corresponding TransactionBatchAppended event.\n    at Object.getExtraData (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/handlers/sequencer-batch-appended.js:22:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async L1IngestionService._syncEvents (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:277:39)\n    at async L1IngestionService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:156:17)\n    at async L1IngestionService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async Promise.all (index 1)\n    at async L1DataTransportService._start (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:69:13)\n    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:33:9)\n    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9"},"msg":"Caught an unhandled error"}
```

**Comment by smartcontracts** [comment]
Sorry for the late reply here. Are you still running into the same issue? This one is pretty interesting, haven't seen it before. If you're still facing the same problem, can start to debug some stuff but will need to ask you for some more info.

**Comment by raffiegang** [comment]
> Sorry for the late reply here. Are you still running into the same issue? This one is pretty interesting, haven't seen it before. If you're still facing the same problem, can start to debug some stuff but will need to ask you for some more info.

Hi smartcontracts. I am happy you answered as Im still stuck. Providing information is not a problem, please tell me what you need!

**Comment by smartcontracts** [comment]
So strange that this is happening. Is this on mainnet or Goerli?

**Comment by raffiegang** [comment]
Mainnet 

> So strange that this is happening. Is this on mainnet or Goerli?

**Comment by Chomtana** [comment]
Stale pre-bedrock issue

Recommend to use either op-erigon or reth for running archive node for now. May integrate them to simple-optimism-node in the future
