### ISSUE TITLE
Help new users with snapshot data

### ISSUE THREAD

**Issue by pleaseshutup** [smartcontracts/simple-optimism-node#42]
Please add instructions for how to get the latest snapshot data to drastically improve the time it takes to get a working node.

**Comment by PierrickGT** [comment]
Snapshots are available here: https://archive.org/download/optimism-snapshot
You need to download the two tar files and export them in the folders where Docker stores the volumes data.
For example on Debian, you would:
- untar `op-replica_dtl-2023-01-17.tar.zst` to `/var/lib/docker/volumes/simple-optimism-node_dtl`
- untar `op-replica_geth-2023-01-17.tar.zst` to `/var/lib/docker/volumes/simple-optimism-node_geth`

**Comment by smartcontracts** [comment]
Thanks @PierrickGT 

I've also integrated a BitTorrent client into `simple-optimism-node` now. I can likely start hosting these over BitTorrent which will be faster than the archive.org downloads once enough people start seeding.

**Comment by smartcontracts** [comment]
Yes I agree, I will add it

**Comment by OliverNChalk** [comment]
Where can I grab the torrent file for the snapshots?

**Comment by eyooooo** [comment]
friendly reminder to anyone who finds this issue - use aria2c to download the snapshots from archive.org.

**Comment by dg123lzk** [comment]
Hello, is this the archive node

**Comment by Chomtana** [comment]
Already have one for full node #97
