### ISSUE TITLE
is there any other place to pull op-node:v0.10.9

### ISSUE THREAD

**Issue by Tokenview** [smartcontracts/simple-optimism-node#47]
I have a setup of ops, but always timeout on this image：us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v0.10.9

**Comment by smartcontracts** [comment]
Latest version is us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.0.0, try that

**Comment by Chomtana** [comment]
Stale pre-bedrock issue
