### ISSUE TITLE
/scripts/check-for-chaindata-berlin.sh: not found

### ISSUE THREAD

**Issue by sanbotto** [smartcontracts/simple-optimism-node#54]
It looks like the image for `l2geth` does not contain the required script since the logs for that container show:

`/bin/sh: /scripts/check-for-chaindata-berlin.sh: not found`

I'm currently pulling `latest` tag. Am I missing something or does the `l2geth` image is actually missing that file?

**Comment by smartcontracts** [comment]
Hmmm can you `docker pull` to get the latest images?

**Comment by sanbotto** [comment]
@smartcontracts the latest update to the `latest` tag was 2 months ago, according to [this](https://hub.docker.com/layers/ethereumoptimism/l2geth/latest/images/sha256-5577036dc36d167d11f5ac49b91cc0a3d835574928a9563783c2e70309e5eb28?context=explore). However, I tested this before opening my issue here and also just now, just to be on the safe side but the issue is the same.

I'm also having issues with `optimism-bedrock-init`, but I want to deal with one issue at a time; I'll open a new one later.

**Comment by sanbotto** [comment]
I noticed the script `/scripts/check-for-chaindata-berlin.sh` is not supposed to be inside the image but rather pulled from this repo, and I quickly realized I was the one doing something wrong... I had copied to my `docker-compose` parts of the entrypoint from my existing node due to how I deploy each node, and that's why said script was trying to be used instead of `/scripts/l2geth-init.sh`.

**Comment by bmalepaty** [comment]
@sanbotto I am facing the same issue. Can you please help me on more details on how you solved the issue?
