### ISSUE TITLE
How do we create our own Metrics?

### ISSUE THREAD

**Issue by platocrat** [smartcontracts/simple-optimism-node#6]
## Question
I wanted to add a new panel to the Simple Dashboard that uses a different query than those used in the pre-existing panels.

How do we create our own Metrics so that we can create new queries?

**Comment by smartcontracts** [comment]
You should be able to just create a new dashboard like you normally would with Grafana. I recommend taking a look at the Grafana docs if you need help figuring out how to put together your first dashboard.

**Comment by smartcontracts** [comment]
Note that changes to the Simple Node Dashboard will not save between restarts, although changes to new dashboards should.

**Comment by smartcontracts** [comment]
Although... I recommend trying to make a simple dashboard with one panel, saving it, then restarting the node just to confirm that it properly saves through restarts. If it doesn't save then I'll need to tweak the setup.
