### ISSUE TITLE
reference client has different hash for block

### ISSUE THREAD

**Issue by hazim-j** [smartcontracts/simple-optimism-node#62]
I'm currently trying to run an Optimism Goerli node on an AWS EC2 instance. It's been running fine and staying in sync up until recently where it started showing the following logs in the `healthcheck-bedrock` service.

Any suggestions on the best way to debug this? Not sure if there's a way to rewind to before the first mismatched block?

```
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":50,"time":1679978541114,"extra":{"blockNumber":7247667,"referenceHash":"0x7cbb1b7dec87e57cc6d9595e7c01b9ab4e68171fa80d0c88149611cd28c32e33","targetHash":"0x83fcd7d2eb802a09c02bf7f1163e41330fa6867f06295fbe4839a4b478352f93"},"msg":"reference client has different hash for block"}
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978541114,"msg":"beginning binary search to find first mismatched block"}
...
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978549847,"blockNumber":6825753,"msg":"checking block"}
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978550335,"blockNumber":6825760,"msg":"checking block"}
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978550814,"blockNumber":6825763,"msg":"checking block"}
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978551308,"blockNumber":6825765,"msg":"checking block"}
simple-optimism-node_testnet-healthcheck-bedrock-1  | {"level":30,"time":1679978551779,"blockNumber":6825766,"msg":"found first mismatched block"}
```

**Comment by almukhametovd** [comment]
Hello @hazim-j 
We had same problem with full and archive nodes

Not sure what happened, we tried to make a wipe and resync, but again stucked on same block

So, we run new ec2 instance with clear node setup with this flag (--p2p.disabled), and it's fully synced with blockchain

**Comment by hazim-j** [comment]
@almukhametovd what was the rationale behind using P2P.disabled flag?

We also spun up a new EC2 instance but with same config and it synched fine.

**Comment by Chomtana** [comment]
Stale pre-bedrock issue
