### ISSUE TITLE
archive node stopped at blockhight 29488322

### ISSUE THREAD

**Issue by bdonglobal** [smartcontracts/simple-optimism-node#63]
I have an archive node, syncing well, until last Friday, it stopped here. Anything I should do to make it continue?

simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:09.689] Historical transaction matches           index=29488321 hash=0x1c6f3305aa7a3c46deb8db55acf6557ed470d79ae1801e3393246919fb1cbaaf
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:09.689] Applying transaction to tip              index=29488322 hash=0x584dc786d2bfb00398bcfbbee7532c3e3f758aed84fc0d8beb9741ebfff20297 origin=sequencer
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:09.689] Attempting to commit rollup transaction  hash=0x584dc786d2bfb00398bcfbbee7532c3e3f758aed84fc0d8beb9741ebfff20297
**simple-optimism-node-l2geth-1  | INFO [04-02|18:02:09.754] New block                                index=29488322 l1-timestamp=1665832027 l1-blocknumber=15753061 tx-hash=0x584dc786d2bfb00398bcfbbee7532c3e3f758aed84fc0d8beb9741ebfff20297 queue-orign=sequencer gas=249989 fees=2.49989e-07 elapsed=64.889ms**
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.009] Served eth_chainId                       conn=192.168.0.4:38364  reqid=1024 t=32.83µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.011] Served eth_getBlockByNumber              conn=192.168.0.4:38380  reqid=1025 t=132.812µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.015] Served eth_chainId                       conn=192.168.0.4:38396  reqid=1026 t=20.85µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.016] Served eth_getBlockByNumber              conn=192.168.0.4:38408  reqid=1027 t=62.231µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.519] Served eth_chainId                       conn=192.168.0.4:38410  reqid=1028 t=35.34µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.520] Served eth_getBlockByNumber              conn=192.168.0.4:38416  reqid=1029 t=132.102µs
simple-optimism-node-l2geth-1  | DEBUG[04-02|18:02:10.524] Served eth_chainId                       conn=192.168.0.4:38432  reqid=1030 t=26.7µs

**Comment by bdonglobal** [comment]
I set the hight to be an older one through setHead, the node continue to sync successfully, but when it sync to 29488322 , stopped again.

curl 'http://127.0.0.1:9991' -H "Content-Type:application/json" -X POST -d '{"jsonrpc":"2.0","method":"debug_setHead","params":["0x1C1F456"],"id":10}'

**Comment by Chomtana** [comment]
Stale pre-bedrock issue
