### ISSUE TITLE
Error: target client not connected

### ISSUE THREAD

**Issue by CheshireCatNick** [smartcontracts/simple-optimism-node#70]
After runniing the node for a while (sync or unsync), I often run into a situation where my health check service cannot connect to L2 provider. When I run the command:
```
docker compose logs healthcheck
```
It always shows
```
{"level":50,"time":1683993055099,"msg":"target client not connected"}
```
Also in the log of fault detector:
```
simple-optimism-node-fault-detector-1          | {"level":30,"time":1683993170652,"msg":"L2 provider not connected, retrying..."}
simple-optimism-node-fault-detector-bedrock-1  | {"level":30,"time":1683993170654,"msg":"L2 provider not connected, retrying..."}
```

I tried to restart my node but nothing works. I'm not sure why this is happening and when I run into this situation, the node is completely not usable. When I try to connect to localhose:9991, it always shows ECONNRESET.

Does anyone encounter the same issue? What else should I check?

**Comment by cryptophonic** [comment]
Same error here
