### ISSUE TITLE
Node syncing is very slow!

### ISSUE THREAD

**Issue by luoxiandong** [smartcontracts/simple-optimism-node#78]
Node syncing slow more and more,How to improve sync speed？
<img width="1367" alt="image" src="https://github.com/smartcontracts/simple-optimism-node/assets/19297244/4287e53f-36de-49f0-bcaf-e94f64a93470">

This is .env config:
<img width="913" alt="image" src="https://github.com/smartcontracts/simple-optimism-node/assets/19297244/d5135376-d2aa-4a0e-9a3b-31f01363c1bf">

**Comment by luoxiandong** [comment]
Does no one reply?
Which big guy replies， tks!!!

**Comment by NickSolante** [comment]
try setting --snapshots=false in https://github.com/smartcontracts/simple-optimism-node/blob/main/scripts/op-geth-start.sh that should speed up the syncing. That sped it up for me when I was syncing it (not through simple-op but through the binary)

**Comment by luoxiandong** [comment]
> try setting --snapshot=false in https://github.com/smartcontracts/simple-optimism-node/blob/main/scripts/op-geth-start.sh that should speed up the syncing. That sped it up for me when I was syncing it (not through simple-op but through the binary)

It is ok,thanks very much!

**Comment by Rogalek** [comment]
hey, can you tell me guys what kind of L1 keys are you using for your optimism node? are they free key from providers like alchemy or infura or something else? or maybe paid? or your L1 nodes?

**Comment by Chomtana** [comment]
Node syncing is known to take weeks

For kind of L1 for now reth may have special protocol that boost performance (Don't sure)

You can use free alchemy but if you want faster L1 rpc, you can use paid Quicknode or Alchemy rpc
