### ISSUE TITLE
Calling docker compose down appears to wipe volumes

### ISSUE THREAD

**Issue by Joseph-Singleton** [smartcontracts/simple-optimism-node#81]
I have tried a few times running the node with docker compose up -d

Checking the logs, all seems to be working well and I can see the block/batch numbers increasing.

When I go to shutdown with docker compose down and then restart the node again, the block/batch numbers restart from zero and the node appears to have completely reset.

Is there something I am doing wrong here?

**Comment by smartcontracts** [comment]
`docker-compose down` won't wipe anything unless you use the `-v` or `--volumes` option which will wipe the volumes that store data. Does `op-node` start from zero or does `op-geth` get reset to zero too?

**Comment by Chomtana** [comment]
Stale

docker compose down doesn't wipe volume
