### ISSUE TITLE
bedrock init error

### ISSUE THREAD

**Issue by luoxiandong** [smartcontracts/simple-optimism-node#82]
Branch:sc/bedrock
Commond:docker-compose --profile current up -d
Error msg:
`
bedrock-init_1    | Extracting bedrock.tar...
bedrock-init_1    | tar: This does not look like a tar archive
bedrock-init_1    | tar: Skipping to next header
bedrock-init_1    | tar: Exiting with failure status due to previous errors
`
How to solve it？

**Comment by yiboGit** [comment]
@luoxiandong  I also have this problem.

**Comment by MHMB** [comment]
Also, I had the same problem, and the `bedrock-init_1` container downloads the `.tar` file slowly.
But in the non-docker setup, the download process only took 30 minutes.

**Comment by Chomtana** [comment]
Hi, my fork has fixed this issue and uses an official snapshot.

Check out https://github.com/Chomtana/simple-optimism-node/tree/main/scripts

Pull request https://github.com/smartcontracts/simple-optimism-node/pull/97

**Comment by smartcontracts** [comment]
Fixed in #97
