### ISSUE TITLE
download bedrock data very slow

### ISSUE THREAD

**Issue by 0xwhatly** [smartcontracts/simple-optimism-node#84]
Env:

- use [simple-optimism-node](https://github.com/smartcontracts/simple-optimism-node) branch is `sc/bedrock`.
- the server is `aws ec2`,and location is `us-east-1
- has open udp and tcp port `6881`

But the data download is very slow
logs:
```
Bedrock node needs to be initialized...
Initializing via download...
Fetching download link...
Downloading bedrock.tar...
Download Progress: 0.00%
Download Progress: 0.00%
Download Progress: 0.00%
Download Progress: 0.01%
Download Progress: 0.01%
Download Progress: 0.01%
^[Download Progress: 0.01%
Download Progress: 0.01%
Download Progress: 0.01%
Download Progress: 0.01%
```

**Comment by 0xwhatly** [comment]
> 

Use you solution,i have download data,but when i start docker,the `simple-optimism-node-op-geth-1` have error log.
![image](https://github.com/smartcontracts/simple-optimism-node/assets/11549225/ab23bb32-fbf0-4259-92b7-6534dcf23264)

**Comment by 0xwhatly** [comment]
In the end, I solved it. thanks @kchojn ,the bedrock data url has change,we can query by [here](https://goerli.etherscan.io/address/0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2#readContract)
the new url is `https://op.datadirs.xyz/mainnet-bedrock.tar`.

**Comment by kchojn** [comment]
Great! Sorry @0xwhatly, I noticed the message only when you tagged me.
My link was from the official documentation: https://community.optimism.io/docs/useful-tools/networks/#, and it worked for me 😅
