### ISSUE TITLE
Snapshot download is inefficient

### ISSUE THREAD

**Issue by feld** [smartcontracts/simple-optimism-node#90]
Currently the bedrock snapshot download runs the download and extraction in separate stages which is very slow and inefficient especially on platforms like EC2. It would be nice if this was reworked to simply pipe the download from wget through `| tar -C /geth -xvf -` so the download and extraction is in one shot, then you don't have to waste time reading and extracting the 400GB you just downloaded...

**Comment by Chomtana** [comment]
Hi, our fork has fixed this issue and use an official snapshot.

Check out https://github.com/Chomtana/simple-optimism-node/tree/main/scripts

Pull request https://github.com/smartcontracts/simple-optimism-node/pull/97
