### ISSUE TITLE
Node stopped syncing at Block 105234895 (Target client not connected)

### ISSUE THREAD

**Issue by bmalepaty** [smartcontracts/simple-optimism-node#94]
I have upgraded my node to Bedrock - But still node is not syncing further.

**.env**

![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/a5e5a9ea-1818-4f51-a507-d274cc41d792)
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/6af9feda-1eb1-441a-88e3-07fd181ac1f5)

**Fault Detector Bedrock Logs:**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/7a3de333-e9d2-45fc-9441-6f5dd49ff9e0)

**Node Healthcheck Bedrock Logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/5dcc0327-0a90-4b9b-abae-c08bb78b5ec0)

**Op-geth logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/b6168e22-ea28-49ee-ac80-b8e5d16b120d)

**Bedrock init logs**
![image](https://github.com/smartcontracts/simple-optimism-node/assets/77955726/4c93c5d5-acf1-4c74-b386-63b3acf008b0)

**Comment by Carl79c** [comment]
Hi, did you resolve it?

**Comment by bmalepaty** [comment]
> Hi, did you resolve it?

No. Unable to find the fix. Can you please help?

**Comment by Carl79c** [comment]
I can't help you. I have the same problem :-)

**Comment by Chomtana** [comment]
Hi, my fork has fixed this issue and uses an official snapshot. It's related to snapshots can't be downloaded properly.

Check out https://github.com/Chomtana/simple-optimism-node/tree/main/scripts

Pull request https://github.com/smartcontracts/simple-optimism-node/pull/97

**Comment by smartcontracts** [comment]
#97 should have fixed this
