### ISSUE TITLE
wget bad option

### ISSUE THREAD

**Issue by A57058** [smartcontracts/simple-optimism-node#96]
https://github.com/smartcontracts/simple-optimism-node/blob/f4db9c52c31d106e37ebcd34ede543880b7f919f/scripts/utils.sh#L20

save file as... -O option, not -o
So, right now file is saved to overlay.

**Comment by Chomtana** [comment]
Hi, my fork has fixed this issue and uses an official snapshot.

Check out https://github.com/Chomtana/simple-optimism-node/tree/main/scripts

Pull request https://github.com/smartcontracts/simple-optimism-node/pull/97

**Comment by smartcontracts** [comment]
#97 has been merged which fixes this, thanks @Chomtana
